// src/styles/theme.js
export const lightTheme = {
    background: '#F9F7F3',
    text: '#333333',
    heading: '#FF6B6B',
    primary: '#FF6B6B',
    primaryLight: '#FF9E9E',
    primaryDark: '#FF3B3B',
    secondary: '#4ECDC4',
    secondaryLight: '#7FDFD8',
    secondaryDark: '#3AA99F',
    accent: '#FFD166',
    accentLight: '#FFE599',
    accentDark: '#FFBA33',
    success: '#6BCD6B',
    error: '#E84855',
    warning: '#FFD166',
    info: '#4A8FE7',
    border: '#E0E0E0',
    cardBg: '#FFFFFF',
    shadow: 'rgba(0, 0, 0, 0.05)',
    shadowStrong: 'rgba(0, 0, 0, 0.1)',
    navbar: '#FFFFFF',
    footer: '#333333',
    footerText: '#FFFFFF',
    foodCardBg: '#FFFFFF',
    foodCardShadow: '5px 5px 0px #FF6B6B',
    buttonHover: 'brightness(110%) scale(1.03)',

    // Caricatura-específico
    outlineColor: '#333',
    outlineWidth: '3px',
    cartoonShadow: '5px 5px 0px rgba(0, 0, 0, 0.2)',
    cartoonGradient: 'linear-gradient(135deg, #FF9E9E 0%, #FF6B6B 100%)',
    buttonGradient: 'linear-gradient(to right, #FF6B6B, #FF9E9E)',
    foodPattern: 'url("/assets/images/pattern-light.svg")',
};

export const darkTheme = {
    background: '#222831',
    text: '#EEEEEE',
    heading: '#FF6B6B',
    primary: '#FF6B6B',
    primaryLight: '#FF9E9E',
    primaryDark: '#FF3B3B',
    secondary: '#4ECDC4',
    secondaryLight: '#7FDFD8',
    secondaryDark: '#3AA99F',
    accent: '#FFD166',
    accentLight: '#FFE599',
    accentDark: '#FFBA33',
    success: '#6BCD6B',
    error: '#E84855',
    warning: '#FFD166',
    info: '#4A8FE7',
    border: '#393E46',
    cardBg: '#393E46',
    shadow: 'rgba(0, 0, 0, 0.2)',
    shadowStrong: 'rgba(0, 0, 0, 0.3)',
    navbar: '#1A1E25',
    footer: '#1A1E25',
    footerText: '#EEEEEE',
    foodCardBg: '#393E46',
    foodCardShadow: '5px 5px 0px #FF6B6B',
    buttonHover: 'brightness(110%) scale(1.03)',

    // Caricatura-específico
    outlineColor: '#000',
    outlineWidth: '3px',
    cartoonShadow: '5px 5px 0px rgba(0, 0, 0, 0.4)',
    cartoonGradient: 'linear-gradient(135deg, #FF9E9E 0%, #FF6B6B 100%)',
    buttonGradient: 'linear-gradient(to right, #FF6B6B, #FF9E9E)',
    foodPattern: 'url("/assets/images/pattern-dark.svg")',
};